### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by znepb** [znepb/gemstone#1]
List of things I want to do before version 1.0:

- [X] Buttons
- [x] Inputs
- [X] Scrollbox
- [x] Text box
- [x] Dropdown
- [ ] Radios
- [ ] Checkboxes
- [x] Raw Buttons (will be used for dropdowns, etc)
- [x] ~~Raw Input (Will be used in regular inputs)~~
- [X] Dialog

The raw elements are just normal elements but without the fancy stuff.

**Comment by vaaski** [comment]
How about an installer or getting started guide?
This looks promising, but I am not sure how it's intended to be used.

**Comment by ghost** [comment]
this isnt an os, this is a drawing api

**Comment by vaaski** [comment]
I know that.
I wanted to play around with it, but I have no idea where to get started. Do I download every file individually? Which files do I need?

That's why I asked for an installer, that downloads all the required files.
Or at least instructions for how to get started.

**Comment by ghost** [comment]
get everything and use require("components.whatever") to load components (oh and . is /)

**Comment by ghost** [comment]
> List of things I want to do before version 1.0:
> 
>     * [x]  Buttons
> 
>     * [x]  Inputs
> 
>     * [x]  Scrollbox
> 
>     * [x]  Text box
> 
>     * [x]  Dropdown
> 
>     * [ ]  Radios
> 
>     * [ ]  Checkboxes
> 
>     * [x]  Raw Buttons (will be used for dropdowns, etc)
> 
>     * [x]  ~Raw Input (Will be used in regular inputs)~
> 
>     * [x]  Dialog
> 
> 
> The raw elements are just normal elements but without the fancy stuff.

might want to add sliders?
